#!/bin/bash

log() {
    local script_name=$(basename "$0")
    local command_executed="$0 $*"
    local exit_status=$?

    ./log.sh "$1" "$2" "$script_name" "$exit_status"
}

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  -h, --help                                 Display this help message"
    echo "  -a, --ask 'question'                       Ask a question to the model"
    echo "  -c, --chat 'question'                      chat to the model"
    echo "  -so, --searchopen 'query'                  Perform an open search which get links for search query"
    echo "  -s, --search 'query'                       Perform a search query which searches and summarize results"
    echo "  -sso, --fullsearch  'query'                Perform both open and search queries"
    echo "  -t  'template_name'                        Show txt inside a specific template file 'template_name'"
    echo "  -tl                                        Show list of templates found"
    echo "  -memshow, --memory_show 'memory_name'      Show Chat model memory"
    echo "  -memclr, --memory_clear 'memory_name'      Clear Chat model memory"
    echo "  -memlst, --memory_list                     show list of memory files found" 
    echo "  -searchshow, --search_show                 show the search history"
    echo "  -searchclr, --search_clear                 Clear the search history"
    echo "  -viewlogs                                  View the log file"
    echo "  -clrlogs                                   Clear the log file"
}

if [ "$#" -eq 0 ]; then
    usage
    log "ERROR" "No options provided"
    echo  echo "Usage: $0 [--ask|-a 'your question to model'] [--searchopen|--so 'your search query'] [--search|--s 'your search query'] [--sso 'your search query']"
    exit 1
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage
    exit 0
fi

log "INFO" "Script started with options: $*"

clrlogs_flag=0

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --ask|-a)
            shift
            log "INFO" "Running ask with input: '$1'"
            ./scripts/run_ask.sh "$1" || { log "ERROR" "Failed to run ask with input: '$1'"; exit 1; }
            ;;
        --chat|-c)
            shift
            log "INFO" "Running chat with input: '$1'"
            ./scripts/run_chat.sh "$1" || { log "ERROR" "Failed to run chat with input: '$1'"; exit 1; }
            ;;
        --searchopen|-so|--search|-s|--fullsearch|-sso)
            shift
            log "INFO" "Running search with option: '$key' and query: '$1'"
            ./scripts/run_search.sh "$key" "$1" || { log "ERROR" "Failed to run search with option: '$key' and query: '$1'"; exit 1; }
            ;;
        -t)
            shift
            log "INFO" "Managing templates with option: '$key' and template: '$1'"
            ./scripts/manage_templates.sh "$key" "$1" || { log "ERROR" "Failed to manage templates with option: '$key' and template: '$1'"; exit 1; }
            ;;
        -tl)
            log "INFO" "Showing list of templates"
            ./scripts/manage_templates.sh -tl || { log "ERROR" "Failed to show list of templates"; exit 1; }
            ;;
        -memshow| --memory_show | -memclr | --memory_clear)
            shift
            log "INFO" "Managing memory with option: '$key' and memory: '$1'"
            ./scripts/manage_memory.sh "$key" "$1" || { log "ERROR" "Failed to manage memory with option: '$key' and memory: '$1'"; exit 1; }
            ;;
        -memlst| --memory_list)
            log "INFO" "Showing list of memory files"
            ./scripts/manage_memory.sh "$key" "$1" || { log "ERROR" "Failed to show list of memory files"; exit 1; }
            ;;
        -searchshow| --search_show| -searchclr| --search_clear)
            log "INFO" "Managing search with option: '$key'"
            ./scripts/manage_search.sh "$key" || { log "ERROR" "Failed to manage search with option: '$key'"; exit 1; }
            ;;
        -viewlogs)
            log "INFO" "Viewing logs"
            ./scripts/manage_logs.sh "$key" || { log "ERROR" "Failed to view logs"; exit 1; }
            ;;
        -clrlogs)
            log "INFO" "Clearing logs"
            ./scripts/manage_logs.sh "$key" || { log "ERROR" "Failed to clear logs"; exit 1; }
            clrlogs_flag=1
            ;;
        *)
            log "ERROR" "Unknown option: '$key'"
            echo "Unknown option: $key"
            usage
            exit 1
            ;;
    esac
    shift
done

if [ $clrlogs_flag -eq 0 ]; then
    log "INFO" "Script execution completed"
fi

exit 0
