#!/bin/bash

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  -h, --help                      Display this help message"
    echo "  -a, --ask 'question'            Ask a question to the model"
    echo "  -c, --chat 'question'           chat to the model"
    echo "  -so, --searchopen 'query'       Perform an open search query"
    echo "  -s, --search 'query'            Perform a search query"
    echo "  -sso, 'query'                   Perform both open and search queries"
    echo "  -t  'template_name'             Show txt inside a specific template file"
    echo "  -tl                             Show list of templates found"
    echo "  -memshow, --memory_show         Show Chat model memory"
    echo "  -memclr, --memory_clear         Clear Chat model memory"
}

if [ "$#" -eq 0 ]; then
    usage
    echo  echo "Usage: $0 [--ask|-a 'your question to model'] [--searchopen|--so 'your search query'] [--search|--s 'your search query'] [--sso 'your search query']"
    exit 1
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage
    exit 0
fi


while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --ask|-a)
            shift
            ./scripts/run_ask.sh "$1" || exit 1
            ;;
        --chat|-c)
            shift
            ./Chat/run_chat.sh "$1" || exit 1
            ;;
        --searchopen|-so|--search|-s|-sso)
            shift
            ./Search/run_search.sh "$key" "$1" || exit 1
            ;;
        -t)
            shift
            ./templates/manage_templates.sh "$key" "$1" || exit 1
            ;;
        -tl)
            ./templates/manage_templates.sh -tl || exit 1
            ;;
        -memshow| --memory_show | -memclr | --memory_clear)
            ./memory/manage_memory.sh "$key" || exit 1
            ;;
        *)
            echo "Unknown option: $key"
            usage
            exit 1
            ;;
    esac
    shift
done

