#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "Usage $0 --searchopen  'your search query'"
    exit 1
fi

python3 model_search.py "$@"

if [ -f tmp_link ]; then
    link=$(cat tmp_link)
    rm tmp_link

    google-chrome "$link"

else
    echo "Error: tmp_link file created by model_search was not created. Ensure the Python script ran successfully."
    exit 1
fi
