from customAgents.agent_llm import SimpleStreamLLM
from customAgents.agent_prompt import SimplePrompt, ReActPrompt
from customAgents.agent_tools import ToolKit, SearchTool, PythonRuntimeTool
from customAgents.agent_runtime import ReActRuntime


from common.utils import load_config, parse_safety_settings
config = load_config(f"../config/llm.json")
safety_settings = parse_safety_settings(config['safety_settings'])


example_workflow = """
Question: What is the date today ?

[you in iteration 1]
Thought: I have to search for the day today using the internet to get a good resault.
Action: search tool
Action Input: today's date

[you then STOP the first iteration after this]


... (not generated by AI it comes as from a software code) Observation: [the tool will return the today's date to you so you have to read the observation carefully to answer in the next step using it (you don't generate observation it just comes to you)]

[you in iteration 2]
Thought: from the previous Observation I can find good and specific information that can answer the user original question which is "What is the date today ?"
Action: finish
Final Answer: Today's date is... [if there is more to describe to make chat more user friendly do it]


Question: What is the product of 22 and 33 ?

[you in iteration 1]
Thought: I have to use python code to find the answer
Action: python tool
Action Input: 
```python

print(22*33)

```

[you then STOP the first iteration after this]

[you in iteration 2]
Thought: from the previous Observation I can find good and specific information that can answer the user original question which is "what is the product of 22 and 33"
Action: finish
Final Answer: the product of 22 * 33 is 726 [if there is more to describe to make chat more user friendly do it]

"""

question = input("Enter you question : ")
llm = SimpleStreamLLM(api_key=config['api_key'],model='gemini-1.5-flash',temperature=0.7,safety_settings=safety_settings)
prompt = ReActPrompt(question=question, example_workflow=example_workflow)
python_tool = PythonRuntimeTool(description="tool that can run python code (give the code for this function as md format)",tool_name="python_tool")
search_tool = SearchTool(description="tool that can search internet (each query you input will get different search)",tool_name="search_tool")
toolkit = ToolKit(tools=[search_tool])
agent = ReActRuntime(llm=llm,prompt=prompt,toolkit=toolkit)

print(agent.loop(agent_max_steps=30))
